### ISSUE TITLE
Overriding indentation

### ISSUE THREAD

**Issue by caseyprovost** [toshimaru/rubocop-rails#21]
Attempting to override indentation for private and protected methods and no dice.

```yaml
inherit_gem:
  rubocop-rails:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.4

Layout/IndentationConsistency:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'config/**/*'
    - Gemfile
    - 'bin/**/*'
    - 'config.ru'
    - 'db/schema.rb'
    - Rakefile
```
