### ISSUE TITLE
Checks inside /vendor/bundle

### ISSUE THREAD

**Issue by saneef** [toshimaru/rubocop-rails#9]
I'm using default `rubocop-rails` settings:
```yml
inherit_gem:
  rubocop-rails:
    - config/rails.yml

```

Still it some how checks inside `/vendor/`

```bash
❯ bundle exec rubocop
Inspecting 130 files
....................C

Offenses:

vendor/bundle/bundler/gems/nexter-823fc8c247bd/.pryrc:2:22: C: Final newline missing.
require "./spec/book"
```
